"import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Link, useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { Dumbbell, ArrowLeft, Calendar, Download, LogOut } from 'lucide-react';
import { Button } from '../components/ui/button';
import { toast } from 'sonner';

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

export default function WorkoutPlanView({ user, onLogout }) {
  const { planId } = useParams();
  const [plan, setPlan] = useState(null);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  useEffect(() => {
    fetchPlan();
  }, [planId]);

  const fetchPlan = async () => {
    try {
      const token = localStorage.getItem('token');
      const response = await axios.get(`${API}/workout-plans/${planId}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setPlan(response.data);
    } catch (error) {
      toast.error('Failed to load workout plan');
      navigate('/dashboard');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!plan) return;

    const content = `
${plan.goal.toUpperCase()} WORKOUT PLAN
Generated by FitPlan

Experience Level: ${plan.experience_level}
Equipment: ${plan.equipment}
Schedule: ${plan.days_per_week} days per week
Duration: ${plan.duration_per_session} minutes per session
Created: ${new Date(plan.created_at).toLocaleDateString()}

${plan.plan_content}
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `workout-plan-${plan.goal.toLowerCase().replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Workout plan downloaded');
  };

  if (loading) {
    return (
      <div className=\"min-h-screen flex items-center justify-center\">
        <div className=\"w-12 h-12 border-4 border-primary border-t-transparent rounded-full animate-spin\"></div>
      </div>
    );
  }

  if (!plan) {
    return null;
  }

  return (
    <div className=\"min-h-screen\">
      {/* Navigation */}
      <nav className=\"fixed top-6 left-1/2 -translate-x-1/2 w-[90%] max-w-5xl glass rounded-full z-50 px-6 py-4\">
        <div className=\"flex items-center justify-between\">
          <Link to=\"/dashboard\" className=\"flex items-center gap-2\">
            <Dumbbell className=\"w-6 h-6 text-primary\" />
            <span className=\"text-xl font-barlow font-bold uppercase tracking-tight\">FitPlan</span>
          </Link>
          <div className=\"flex items-center gap-4\">
            <span className=\"text-sm text-muted-foreground hidden md:block\">Welcome, {user?.name}</span>
            <Button
              data-testid=\"logout-btn\"
              onClick={onLogout}
              variant=\"ghost\"
              size=\"sm\"
              className=\"hover:bg-white/5 text-gray-300 hover:text-white\"
            >
              <LogOut className=\"w-4 h-4\" />
            </Button>
          </div>
        </div>
      </nav>

      <div className=\"pt-32 px-6 pb-12\">
        <div className=\"max-w-4xl mx-auto\">
          {/* Header */}
          <Link to=\"/dashboard\">
            <Button 
              data-testid=\"back-to-dashboard-btn\"
              variant=\"ghost\" 
              className=\"mb-8 hover:bg-white/5 text-gray-300 hover:text-white\"
            >
              <ArrowLeft className=\"w-4 h-4 mr-2\" />
              Back to Dashboard
            </Button>
          </Link>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            {/* Plan Header */}
            <div className=\"glass p-8 rounded-sm glow-border mb-6\">
              <div className=\"flex items-start justify-between mb-6\">
                <div>
                  <h1 data-testid=\"plan-title\" className=\"text-4xl md:text-6xl font-black font-barlow uppercase tracking-tighter mb-2\">
                    {plan.goal}
                  </h1>
                  <div className=\"flex items-center gap-2 text-muted-foreground\">
                    <Calendar className=\"w-4 h-4\" />
                    <span>Created {new Date(plan.created_at).toLocaleDateString()}</span>
                  </div>
                </div>
                <Button
                  data-testid=\"download-plan-btn\"
                  onClick={handleDownload}
                  className=\"bg-white/5 hover:bg-white/10 text-white border border-white/10 font-bold uppercase tracking-wider rounded-sm\"
                >
                  <Download className=\"w-4 h-4 mr-2\" />
                  Download
                </Button>
              </div>

              <div className=\"grid grid-cols-2 md:grid-cols-4 gap-4\">
                <div>
                  <div className=\"text-xs text-muted-foreground uppercase tracking-wide mb-1\">Experience</div>
                  <div className=\"font-bold\">{plan.experience_level}</div>
                </div>
                <div>
                  <div className=\"text-xs text-muted-foreground uppercase tracking-wide mb-1\">Equipment</div>
                  <div className=\"font-bold\">{plan.equipment}</div>
                </div>
                <div>
                  <div className=\"text-xs text-muted-foreground uppercase tracking-wide mb-1\">Frequency</div>
                  <div className=\"font-bold\">{plan.days_per_week} days/week</div>
                </div>
                <div>
                  <div className=\"text-xs text-muted-foreground uppercase tracking-wide mb-1\">Duration</div>
                  <div className=\"font-bold\">{plan.duration_per_session} min</div>
                </div>
              </div>
            </div>

            {/* Plan Content */}
            <div className=\"glass p-8 rounded-sm\">
              <h2 className=\"text-2xl font-bold font-barlow uppercase mb-6 text-primary\">Your Personalized Plan</h2>
              <div 
                data-testid=\"plan-content\"
                className=\"prose prose-invert max-w-none\"
                style={{
                  whiteSpace: 'pre-wrap',
                  lineHeight: '1.8',
                  fontSize: '1rem',
                  color: '#E4E4E7'
                }}
              >
                {plan.plan_content}
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </div>
  );
}
"
